# Generated by Django 4.1.3 on 2022-11-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('Collect', 'Collect'), ('Collected', 'Collected'), ('Report', 'Report')], default='Collect', max_length=50),
        ),
    ]
