# Generated by Django 4.1.3 on 2022-11-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patientnotes_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultbillingledger',
            name='patientStatus',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Admitted', 'Admitted'), ('Outpatient', 'Outpatient'), ('Discharged', 'Discharged')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Admitted', 'Admitted'), ('Outpatient', 'Outpatient'), ('Discharged', 'Discharged')], max_length=100, null=True),
        ),
    ]
