# Generated by Django 4.1.3 on 2022-11-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sampletypetest_sampleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletypetest',
            name='sampleType',
        ),
        migrations.AddField(
            model_name='sample',
            name='sampleType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sampletype'),
        ),
    ]
