# Generated by Django 4.1.3 on 2022-11-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_sampletypetest_sampletype_sample_sampletype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleList',
        ),
    ]
