# Generated by Django 4.1.3 on 2022-11-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_samplelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sampleType',
        ),
        migrations.RemoveField(
            model_name='sampletest',
            name='reference_end_range',
        ),
        migrations.RemoveField(
            model_name='sampletest',
            name='reference_start_range',
        ),
        migrations.RemoveField(
            model_name='sampletypetest',
            name='field',
        ),
        migrations.RemoveField(
            model_name='sampletypetest',
            name='sampleTest',
        ),
        migrations.AddField(
            model_name='sampletypetest',
            name='sampleTest',
            field=models.ManyToManyField(to='api.sampletest'),
        ),
    ]
