# Generated by Django 4.1.3 on 2022-11-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_sample_sampletype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletypetest',
            name='field',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
