from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Company)
admin.site.register(FiscalYear)
admin.site.register(Prefix)
admin.site.register(Role)
admin.site.register(DoctorMapping)
admin.site.register(DoctorSchedule)
admin.site.register(Holiday)
admin.site.register(BillingMode)
admin.site.register(Department)
admin.site.register(Consultant)
admin.site.register(ServiceCost)
admin.site.register(ServiceGroup)
admin.site.register(ReferCorporation)
admin.site.register(Referby)
admin.site.register(Medicine)
admin.site.register(Standard)
admin.site.register(Manufacturer)
admin.site.register(PackSize)
admin.site.register(Generic)
admin.site.register(GenericStrength)
admin.site.register(Unit)
admin.site.register(SurgicalGroup)
admin.site.register(Surgical)
admin.site.register(SurgicalItem)
admin.site.register(Size)
admin.site.register(Group)
admin.site.register(ExtraItem)
admin.site.register(ShareSetting)
admin.site.register(TypePatient)
admin.site.register(ServicePackageCategory)
admin.site.register(ServicePackage)
admin.site.register(Menu)
admin.site.register(DiscoutCategory)
admin.site.register(BillingFraction)
admin.site.register(Symptom)
admin.site.register(SymptomMapping)
admin.site.register(CustomReport)
admin.site.register(CustomForm)
admin.site.register(ClaimPrefix)
admin.site.register(PatientSchemeDiscount)
admin.site.register(JournalVoucherSub)
admin.site.register(Patient)
admin.site.register(Bill)
admin.site.register(Charge)
admin.site.register(PrimaryDiagnosis)
admin.site.register(TotalPayment)
admin.site.register(TotalCharge)
admin.site.register(Sample)
admin.site.register(SampleTest)
admin.site.register(SampleType)
admin.site.register(SampleTypeTest)
admin.site.register(User)
admin.site.register(Room)

# New registers
admin.site.register(PatientVisit)
admin.site.register(PatientNotes)
admin.site.register(PatientAppointment)
admin.site.register(PatientVisitType)
# New registers 11/14/2022
admin.site.register(PatientAllergies)
admin.site.register(CurrentOperativePlan)
admin.site.register(PatientSurgery)
admin.site.register(Emergency)
admin.site.register(Payment)



